### ISSUE TITLE
Parse arguments to app.sh

### ISSUE THREAD

**Issue by spygi** [spygi/timetrckr#1]

**Comment by spygi** [comment]
ChangeDirectory on the launchd
1. Command line parameters
2. config file

**Comment by spygi** [comment]
Parameters:
file, outputfile, threshold (rename), lunchstartstop, nightstartstop (rename)

command line parameters:
-f for config file?
-s to produce summary see #14. Offer 2 options: yesterday or all

**Comment by spygi** [comment]
@spygi

**Comment by spygi** [comment]
@spyros86 any ideas how to do this? getopts?

**Comment by devspyrosv** [comment]
Since you know the number of possible arguments, it's best to avoid just using "shift".
Using "getopts" is tedious but the best way nonetheless. You can always use $1 $2 ... $N but then you have to be careful about the command syntax.

**Comment by devspyrosv** [comment]
#!/bin/bash
while getopts ":epilogh" opt; do
  case $opt in
    epilogh)
      echo "-epilogh selected" >&2;
    ;
    \?)
      echo "Invalid arg: -$OPTARG" >&2;
      ;
  esac
done

**Comment by spygi** [comment]
Thanks man, here are some :beers: :+1:

**Comment by spygi** [comment]
FYI nice resource http://wiki.bash-hackers.org/howto/getopts_tutorial

**Comment by spygi** [comment]
Parsing files in 7d9bc78c0d2e9b0af61852eb965436972f72cd40

**Comment by spygi** [comment]
parsing command line arguments as well in 9c02b956ef595dce9912d5b6918cf1a9d9c7f184
